### ISSUE TITLE
The results on val set for the Cyclist and Pedestrian are poor.

### ISSUE THREAD

**Issue by KuofengGao** [xinzhuma/monodle#31]
My config file is
```
random_seed: 444

dataset:
  type: &dataset_type 'KITTI'
  batch_size: 16
  use_3d_center: True
  class_merging: False
  use_dontcare: False
  bbox2d_type: 'anno'   # 'proj' or 'anno'
  meanshape: False      # use predefined anchor or not
  writelist: ['Cyclist']
  random_flip: 0.5
  random_crop: 0.5
  scale: 0.4
  shift: 0.1

model:
  type: 'centernet3d'
  backbone: 'dla34'
  neck: 'DLAUp'
  num_class: 3

optimizer:
  type: 'adam'
  lr: 0.00125
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  decay_list: [90, 120]

trainer:
  max_epoch: 140
  gpu_ids: 0
  save_frequency: 140 # checkpoint save interval (in epoch)
  # resume_model: 'checkpoints/checkpoint_epoch_70.pth'

tester:
  type: *dataset_type
  mode: single   # 'single' or 'all'
  checkpoint: 'checkpoints/checkpoint_epoch_140.pth'  # for 'single' mode
  checkpoints_dir: 'checkpoints'  # for 'all' model
  threshold: 0.2  # confidence filter
```
The result is 
```
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:60.4823, 37.8863, 37.4410
bev  AP:4.1831, 3.0303, 3.0303
3d   AP:4.0485, 3.0303, 3.0303
aos  AP:45.38, 28.43, 28.28
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:58.2341, 36.6064, 34.5565
bev  AP:2.0704, 1.0495, 1.0625
3d   AP:1.5404, 0.9058, 0.9495
aos  AP:43.49, 26.83, 25.58
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:60.4823, 37.8863, 37.4410
bev  AP:19.2926, 12.4708, 12.7571
3d   AP:18.0520, 11.7132, 11.4754
aos  AP:45.38, 28.43, 28.28
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:58.2341, 36.6064, 34.5565
bev  AP:17.9160, 9.2285, 9.1716
3d   AP:15.9519, 8.5839, 8.2388
aos  AP:43.49, 26.83, 25.58
```
